<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Autonomous E-commerce Website</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Shop</a></li>
                <li><a href="#">Cart</a></li>
                <li><a href="#">Login</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <section id="hero">
            <h1>Welcome to our Autonomous E-commerce Website!</h1>
            <p>Shop with us today!</p>
        </section>
        <section id="products">
            <h2>Our Products</h2>
            <div class="products-grid">
                <!-- Products will be rendered here -->
            </div>
        </section>
    </main>
    <footer>
        <p>&copy; 2023 Autonomous E-commerce Website</p>
    </footer>
    <script src="script.js"></script>
</body>
</html>
